openapi: 3.0.1
info:
  title: User API
  description: API for user management
  version: 1.0.0
paths:
  /users/signup:
    post:
      summary: Register a new user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                phone:
                  type: number  
                email:
                  type: string
                password:
                  type: string
                street:
                  type: object
                  properties:
                    number:
                      type: number  
                    postalCode:
                      type: number
                    floor:
                      type: number
                    apartment:
                      type: string
      responses:
        201:
          description: User created successfully
        400:
          description: Bad request
  /users/login:
    post:
      summary: Login a user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Login successful
        401:
          description: Unauthorized
