openapi: 3.0.1
info:
  title: Appointment API
  description: API for managing appointments
  version: 1.0.0
paths:
  /appointments/appointment:
    post:
      summary: Create a new appointment
      tags:
        - Appointments
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                patientName:
                  type: string
                doctorName:
                  type: string
                date:
                  type: string
                  format: date-time
                reason:
                  type: string
      responses:
        201:
          description: Appointment created successfully
        400:
          description: Bad request
  /appointments/allAppointment:
    get:
      summary: Get all appointments
      tags:
        - Appointments
      security:
        - bearerAuth: []
      responses:
        200:
          description: List of all appointments
        404:
          description: Appointments not found
